### ISSUE TITLE
(feat): Add an option for filtering components

### ISSUE THREAD

**Issue by vogloblinsky** [compodoc/ngd#19]
Option for excluding components with Regex or prefixes

**Comment by manekinekko** [comment]
@vogloblinsky any status for this one?

**Comment by vogloblinsky** [comment]
I don't know if it is necessary. What if the percentage of people who will exclude components from a main graph ?

**Comment by manekinekko** [comment]
very low I guess. i'll close this and if someone ask for it, let's just re-open it.
