### ISSUE TITLE
(feat): add a library mode

### ISSUE THREAD

**Issue by vogloblinsky** [compodoc/ngd#36]
`const ngd = require('angular2-dependencies-graph')`

which APIs opened ?
- getDependencies : return json file as javascript object
- renderGraph

**Comment by manekinekko** [comment]
see this first implementation: https://github.com/compodoc/angular2-dependencies-graph/blob/v2/src/modules/cli/src/index.ts#L4-L6

**Comment by vogloblinsky** [comment]
Me too ;) : https://github.com/compodoc/compodoc/releases/tag/0.0.24
