### ISSUE TITLE
CLI Silent Option Doesn't Work

### ISSUE THREAD

**Issue by bwsinger** [compodoc/ngd#52]
The CLI option `--silent` and `-s` doesn't do anything.
(Version: 2.0.0-alpha.5)

![ngdissue](https://user-images.githubusercontent.com/16724046/33524541-fa5172d4-d7d3-11e7-85b6-f1b6f292a5fa.gif)

**Comment by manekinekko** [comment]
the silent option was muting the CLI logs but not the compiler's logs.
fixed in v2.0.0 (will be published to npm soon). cc @vogloblinsky
