### ISSUE TITLE
dot npm package vulnerability (npm audit failing)

### ISSUE THREAD

**Issue by dennisporterjr** [compodoc/ngd#59]
##### **Overview of the issue**

Current Compodoc/ngd version (in master) depends on dot@1.1.1, which contains the vulnerability identified here:

https://www.npmjs.com/advisories/798

This is causing npm audit checks to break.

##### **Operating System, Node.js, npm, compodoc version(s)**

Looks like this dependency was added 2 years ago. And all versions of dot are affected.

https://github.com/compodoc/ngd/commit/bb3c75cc3de493f5339320e3250389805b4d6b6b

##### **Suggest a Fix**

Doesn't look like dot is actively developed any more because the last release was [2 years ago](https://github.com/olado/doT/releases). So I think you'd need to replace it with a different npm package.

**Comment by manekinekko** [comment]
Thanks @dennisporterjr for reporting this.

@vogloblinsky this fix has landed in https://github.com/compodoc/ngd/pull/58/commits/78345d493baa494e81851c3abc30db3ff1a102fb can you cut a new release please?

**Comment by dennisporterjr** [comment]
@manekinekko just want to double check... are we sure that that version bump fixes the vulnerability? the npm advisory looks like it's saying all versions of dot have it.

**Comment by manekinekko** [comment]
Oh I see. Yeah I think we could easily use an alternative templating engine from [these](https://www.npmjs.com/search?q=keywords:template).

**Comment by jscharett** [comment]
Is anyone working on this?

**Comment by maktarsis** [comment]
Let's try one more time. 
Should we expect the fix in the near future?

**Comment by vogloblinsky** [comment]
@maktarsis @jscharett we are watching that. for ngd, there is not dot updates since 2 years. for compodoc, i think i will remove the dependency of ngd in the next major release, the graphic engine for modules will be client side.

**Comment by vogloblinsky** [comment]
Version bumped
