### ISSUE TITLE
NGD does not recognise -l or --files option

### ISSUE THREAD

**Issue by jmacura** [compodoc/ngd#66]
**Describe the bug**
ngd does not recognise `-l` option (neither `--files` option), which is documented in README.md.

**To Reproduce**
1. `npm i -g @compodoc/cli`
2. e.g. `ngd -l .\app.module.ts .\components\core\core.module.ts`
3. NGD does not recognise this option and tries to use `tsconfig.json` instead (which does not contain entry `files`, hence the consequent SyntaxError).

**Expected behavior**
NGD should resolve all files listed (I guess, not documented).

**Screenshots**
![image](https://user-images.githubusercontent.com/5598693/88597805-5c2f4780-d068-11ea-8893-e8e9e9555bc3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - CLI: Windows Terminal (PowerShell)

**Additional context**
None

**Comment by vogloblinsky** [comment]
Option removed
