### ISSUE TITLE
Since 2.1, `@compodoc/ngd-transformer` now requires Node >= 12.17.0

### ISSUE THREAD

**Issue by gaetanmaisse** [compodoc/ngd#68]
**Describe the bug**

The latest release of `@compodoc/ngd-transformer` includes https://github.com/compodoc/ngd/commit/60dbb2ac17e1d87f75b2378975607e578ae2a1fd. 
In this commit, `viz.js` has been replaced by `@aduh95/viz.js` ([here](https://github.com/compodoc/ngd/commit/60dbb2ac17e1d87f75b2378975607e578ae2a1fd#diff-6c5c9203f812d779a231cc2533ea0207R30)).

Functionality speaking it looks ok however node requirement of `@aduh95/viz.js` is stricter than `viz.js` as it needs `^12.17.0 || >=13.2.0`, see: https://github.com/aduh95/viz.js/blob/master/package.json#L24. 

It can look irrelevant but as this was published in a minor release and as `@compodoc/compodoc` has a dependency on `"@compodoc/ngd-transformer": "^2.0.0"` (^2.1.0 for a few hours) it causes the following error when running `yarn install` with Node <12.17.0 : 

> error @aduh95/viz.js@3.1.0: The engine "node" is incompatible with this module. Expected version "^12.17.0 || >=13.2.0". Got "12.16.2"
error Found incompatible module.

And it's breaking some of the CI steps of [Storybook](https://github.com/storybookjs/storybook) for instance.

**Expected behavior**

Builds of `@compodoc/compodoc` users should not be broken because one of its dependency had a minor release.

**Additional context**

Options I have in mind: 
 - Check with the maintainer of `@aduh95/viz.js` if current node requirement (`"^12.17.0 || >=13.2.0"`) is correct. It has been bumped [here](https://github.com/aduh95/viz.js/commit/667d441a20434fe009862a2921438ed9b4272039) but there is no info about the reason in the commit message.
 - Update Node compatibility and make major releases of `@compodoc/ngd-transformer` and `@compodoc/compodoc` and so on Storybook side we will safely use an old/fixed version of Compodoc for now.

**Comment by aduh95** [comment]
I've published `@aduh95/viz.js` `v3.2.0` which removes the engine restriction. PTAL.

**Comment by gaetanmaisse** [comment]
Closing as everything is back to 🟢  with the 3.2.0 release of `@aduh95/viz.js`
