### ISSUE TITLE
(feat): add a client version of this tool

### ISSUE THREAD

**Issue by manekinekko** [compodoc/ngd#8]
Currently, this tool runs on the server ([Node](https://github.com/manekinekko/angular2-dependencies-graph/tree/master/src/platform/node)). We need to add a client version so a developer can generate a live view of the application's deps.

We may look at [D3.js](https://github.com/mbostock/d3/wiki/Gallery) for the visual part. This step should be straightforward. However, we need to write a client version of the [crawler](https://github.com/manekinekko/angular2-dependencies-graph/blob/master/src/platform/node/crawlers/dependencies.ts).

Of course, we also need to clean up all the references to the Node environment.

**Comment by web-dave** [comment]
I want to figure out the effort to make a vscode extension from this.

**Comment by manekinekko** [comment]
Hi @web-dave 
I guess this could be done in 1 day. See: https://code.visualstudio.com/Docs/extensions/example-hello-world

**Comment by manekinekko** [comment]
I've created another issue if you're interested (https://github.com/manekinekko/angular2-dependencies-graph/issues/17)
